language: php

php:
  - 7.1.11

services:
  - mysql

sudo: false

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS employee;'

before_script:
  - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev install
  - bin/console doctrine:database:create
  - bin/console doctrine:schema:update --force
  - bin/console doctrine:fixtures:load --append
  - bin/console doctrine:fixtures:load --append
  - bin/console doctrine:fixtures:load --append
  - bin/console doctrine:fixtures:load --append

test:
  adapter: mysql2
  database: employee
  username: root
  encoding: utf8

script: phpunit


dist: precise