language: php

php:
  - 7.1.11

services:
  - mysql

before_install:
  #- mysql -e 'CREATE DATABASE IF NOT EXISTS myapp_test;'

before_script:
  - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev install
  - bin/console doctrine:database:create
  - bin/console doctrine:schema:update --force
  - bin/console doctrine:fixtures:load --append
  - bin/console doctrine:fixtures:load --append


test:
  #adapter: mysql2
  database: employee_test
  username: travis
  encoding: utf8

script: vendor/bin/phpunit


#dist: precise