<?php

namespace AppBundle\Repository;
/**
 * CrudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository;
class CrudRepository extends EntityRepository
{

    public function searchByName($name)
    {
        return $this->createQueryBuilder('a')
            ->where('a.name LIKE :name')
            ->setParameter('name', '%'.$name.'%')
            ->getQuery()
            ->getResult();
    }

    public function findAgeGreaterThan($age)
    {
        $ag = $this->createQueryBuilder('a')
            ->andWhere('a.age > :age')
            ->setParameter('age', $age)
            ->orderBy('a.age', 'ASC')
            ->getQuery();

        return $ag->execute();
    }


}
