<?php

namespace AppBundle\Repository;
/**
 * EmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository;
class EmployeeRepository extends EntityRepository
{
    public function searchByName($name)
    {
        return $this->createQueryBuilder('a')
            ->where('a.name LIKE :name')
            ->setParameter('name', '%'.$name.'%')
            ->getQuery()
            ->getResult();
    }
    public function findAgeGreaterThan($age)
    {
        return $this->createQueryBuilder('a')
            ->andWhere('a.age > :age')
            ->setParameter('age', $age)
            ->orderBy('a.age', 'ASC')
            ->getQuery();
    }
}
