# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
            AppBundle\Entity\User: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        my_db_provider:
              entity:
                    class: AppBundle\Entity\User
                    property: username
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_firewall:
              pattern: ^/auth/
              anonymous: ~
        main:
            pattern: ^/employee
            provider: my_db_provider

        #    # activate different ways to authenticate#
        #    # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                 login_path: access
                 check_path: /employee/login_check

            logout:
                 path: /employee/logout
                 target: /employee

    access_control:
              - { path: ^/auth/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
              - { path: ^/auth/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
